### PR TITLE
updated the source and cleaned-up the repo

### PR DESCRIPTION
**Pull request by hindujachennupati**
Update the source in all the folder
Clean up unwanted folders

### CODE REVIEW

**Comment by mayank0202** [comment]
Are we supposed to remove eks folder? and can we add any other arc service folder in template? @jamescrowley321  @tsaucier-sf

**Comment by tsaucier-sf** [comment]
> Are we supposed to remove eks folder? and can we add any other arc service folder in template? @jamescrowley321 @tsaucier-sf

@hindujachennupati remove the EKS folder since we do not currently use / regularly maintain it.

**Review by tsaucier-sf — APPROVED** [review]

**Comment by mayank0202** [comment]
> > Are we supposed to remove eks folder? and can we add any other arc service folder in template? @jamescrowley321 @tsaucier-sf
> 
> @hindujachennupati remove the EKS folder since we do not currently use / regularly maintain it.

Its removed @tsaucier-sf

**Review by mayank0202 — APPROVED** [review]

**Comment by hindujachennupati** [comment]
> > Are we supposed to remove eks folder? and can we add any other arc service folder in template? @jamescrowley321 @tsaucier-sf
> 
> @hindujachennupati remove the EKS folder since we do not currently use / regularly maintain it.

@tsaucier-sf - I removed EKS folder

**Review by jamescrowley321 — APPROVED** [review]

**Pull request merged**
